#define KERNEL_BASE 
#define KERNEL_MAP 
#define KERNEL_TASK 
#define BZERO 
#define BCOPY 
#define COPYIN 
#define COPYOUT 
#define ROOTVNODE 
#define KAUTH_CRED_REF 
#define HOST_PRIV_SELF 
#define IPC_PORT_ALLOC_SPECIAL 
#define IPC_KOBJECT_SET 
#define IPC_PORT_MAKE_SEND 
#define CHG_PROC_CNT 
#define VERSION 
